package com.Harbinger.Spore.Sentities.Animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class UmarmerAnimations {

    public static final AnimationDefinition UMARMER_IDLE = AnimationDefinition.Builder.withLength(6f).looping()
            .addAnimation("Tendril_organoid1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("BiomassCrown1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 1f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2083435f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 1f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.25f, KeyframeAnimations.posVec(0f, 1f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("BiomassCrown2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.posVec(2f, 2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H1Head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-0.14f, 3.12f, 0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.5f, KeyframeAnimations.degreeVec(-0.14f, 3.12f, 0.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H1Arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -52.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(-27.5f, 0f, -52.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Human2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-7.26f, -4.56f, -5.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(-10.66f, -0.38f, 6.88f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H2Details",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.7916765f, KeyframeAnimations.posVec(0f, 0.25f, 0.5f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.875f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H2Details",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.208343f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H2Arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.875f, KeyframeAnimations.degreeVec(13.92f, -13.69f, -4.95f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Human3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-4.99f, -0.76f, -2.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-4.57f, 4.11f, -2.82f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(2.51f, -0.76f, -2.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(-4.56f, -3.33f, -1.9f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("TorsoDetials",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("TorsoDetials",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.9583435f, KeyframeAnimations.scaleVec(1.2f, 1.3f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H3Head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(15.17f, -5.17f, -1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(15.17f, -5.17f, -1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(26.78f, 20.29f, 9.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(54.28f, 20.29f, 9.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.posVec(0.75f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-155.71f, 70.95f, 211.08f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT3",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6766666f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.8343333f, KeyframeAnimations.posVec(0f, 0f, -0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.posVec(-0.5f, -0.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.375f, KeyframeAnimations.posVec(-0.5f, -1.25f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("MT3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(10.14f, 15f, -12.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(3.18f, -2.73f, -27.94f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("H3Arms",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-22.87f, -3.25f, 25.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(4.39f, 27.73f, 40.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tendril1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.375f, KeyframeAnimations.degreeVec(-19.18f, -23.77f, 7.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(12.1f, 11.91f, -3.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-7.9f, 11.91f, -3.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(-8.73f, -27.7f, 1.91f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tendril2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-12.5f, 0f, 32.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(-25f, 0f, 32.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(10.08f, -7.39f, 31.19f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(9.33f, -31.79f, 12.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tendril3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766666f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(-33.58f, 15.94f, 30.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.625f, KeyframeAnimations.degreeVec(16.42f, 15.94f, 30.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(25.82f, -10.48f, 8.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tendril4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-33.97f, 18.54f, -14.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(-5.64f, 11.16f, -12.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(35.43f, 4.45f, -11.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-4.62f, -6.11f, -9.74f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(25.38f, -6.11f, -9.74f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(4.74f, 6.43f, 19.22f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(15f, 12.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(19.98f, 7.97f, 26.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(17.12f, -0.83f, 20.84f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.875f, KeyframeAnimations.degreeVec(17.32f, -15.16f, 12.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Rib1Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.7083434f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.6766667f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.75f, KeyframeAnimations.degreeVec(-5f, -5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.458343f, KeyframeAnimations.degreeVec(2.5f, -5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(2.61f, 17.48f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib1Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, 20f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.degreeVec(-16.5f, 5.65f, 4.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(18.5f, 5.65f, 4.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.375f, KeyframeAnimations.degreeVec(1.6f, 15.12f, 7.76f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Rib2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(-10.14f, 17.9f, -20.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(20.26f, 12.24f, 6.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(23.29f, 26.35f, 12.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(27.82f, 7.65f, 18.36f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(17.6f, 16.75f, -7.07f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.583433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib2Details",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0.20834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1.3f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.0834335f, KeyframeAnimations.scaleVec(1f, 1f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0416765f, KeyframeAnimations.scaleVec(1.1f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib2Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(0f, 35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-15f, 12.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(5f, -75f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.041677f, KeyframeAnimations.degreeVec(1.3f, -7.55f, 4.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.791677f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib2Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(1.2083433f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.875f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.041677f, KeyframeAnimations.degreeVec(0f, 32.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(-10.33f, -9.24f, -14.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(3.08f, 6.55f, 12.78f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.834333f, KeyframeAnimations.degreeVec(3.13f, -20.82f, 15.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib3Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(11.25f, 0.25f, 22.52f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.3433335f, KeyframeAnimations.degreeVec(14.51f, -38.83f, 13.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.541677f, KeyframeAnimations.degreeVec(24.95f, -33.72f, -4.28f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(37.45f, -33.72f, -4.28f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib3Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(-10f, 20f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0834335f, KeyframeAnimations.degreeVec(-9.43f, -15.57f, 5.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(-5.91f, 15.09f, 0.92f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, -27.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5416765f, KeyframeAnimations.degreeVec(-12.7f, 22.52f, 13.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-2.89f, 36f, -11.78f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.125f, KeyframeAnimations.degreeVec(13.82f, 3.91f, -8.44f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib4Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(8.53f, 2.9f, 14.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9167665f, KeyframeAnimations.degreeVec(7.72f, -38.43f, 29.73f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.375f, KeyframeAnimations.degreeVec(19.88f, -60.61f, 23.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib4Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 67.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.degreeVec(30.04f, 76.71f, 13.13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(-147.06f, 87.91f, -129.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib5",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583434f, KeyframeAnimations.degreeVec(0f, 42.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(-7.14f, 59.04f, 14.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(-16.96f, 5.35f, 13.25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.458343f, KeyframeAnimations.degreeVec(-5.4f, -4.07f, 3.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.291677f, KeyframeAnimations.degreeVec(-10.13f, 15.64f, -0.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib5Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(0f, -30f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5416765f, KeyframeAnimations.degreeVec(-12.97f, -3.28f, -6.88f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.625f, KeyframeAnimations.degreeVec(71.73f, 80.88f, 76.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.75f, KeyframeAnimations.degreeVec(-17.87f, 68.89f, -35.15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.458343f, KeyframeAnimations.degreeVec(-6.99f, 24.66f, -21.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib5Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.3433335f, KeyframeAnimations.degreeVec(-17.5f, -50f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(40.18f, -75.06f, -27.61f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.291677f, KeyframeAnimations.degreeVec(11.13f, -30.5f, 5.9f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.083433f, KeyframeAnimations.degreeVec(-1.83f, -57.26f, 30.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib5Seg4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, KeyframeAnimations.degreeVec(0f, -57.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(-14.04f, -25.9f, 14.43f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(7.17f, 10.64f, 5.79f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.125f, KeyframeAnimations.degreeVec(15.9f, -63.39f, -9.83f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.875f, KeyframeAnimations.degreeVec(22.3f, -43.85f, -2.36f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib6",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.1676665f, KeyframeAnimations.degreeVec(-7.5f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.875f, KeyframeAnimations.degreeVec(3.69f, -12.87f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(8.44f, 4.3f, -1.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(-3.39f, 7.25f, 2.6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib6Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.8343333f, KeyframeAnimations.degreeVec(20.01f, 28.48f, 9.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.8343335f, KeyframeAnimations.degreeVec(10.35f, -21.57f, -16.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(17.94f, 23.92f, 8.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(12.37f, 20.05f, -17.15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(20.3f, -35.75f, -11.57f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.541677f, KeyframeAnimations.degreeVec(16.59f, -9.6f, -2.22f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib6Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.125f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083435f, KeyframeAnimations.degreeVec(30f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(2.5f, -17.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib7",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.3433333f, KeyframeAnimations.degreeVec(0f, -25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-12.5f, -25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.2083435f, KeyframeAnimations.degreeVec(0.92f, -14.77f, -23.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.375f, KeyframeAnimations.degreeVec(16.46f, 0.1f, -25.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.791677f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib7Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 20f, -27.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(-35.39f, 41.47f, -42.6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(24.39f, 61.81f, 35.02f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.541677f, KeyframeAnimations.degreeVec(-34.34f, 76.69f, -3.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.375f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Rib7Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-15.69f, 16.89f, -4.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(-32.37f, -61.09f, 29.02f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.degreeVec(-4.06f, -28.73f, 24.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MouthGrowth1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167666f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(12.09f, -3.21f, 14.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9583435f, KeyframeAnimations.degreeVec(-8.1f, -7.3f, -10.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.208343f, KeyframeAnimations.degreeVec(6.9f, -7.3f, -10.11f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MouthGrowth2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0834333f, KeyframeAnimations.degreeVec(-17.5f, 0f, 35f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(113.5f, -33.56f, -100.36f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5834335f, KeyframeAnimations.degreeVec(88.5f, -33.56f, -100.36f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(-21.82f, -5.72f, 11.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.625f, KeyframeAnimations.degreeVec(-16.99f, -5.12f, -14.84f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.708343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MouthGrowth3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-19.64f, 19.76f, 10.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1676667f, KeyframeAnimations.degreeVec(42.48f, -13.38f, -62.09f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.0834335f, KeyframeAnimations.degreeVec(46.91f, 20.85f, -40.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.375f, KeyframeAnimations.degreeVec(102.56f, -1.77f, -102.94f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MouthGrowth4",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5834333f, KeyframeAnimations.degreeVec(184.75f, 31.26f, -154.28f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2916765f, KeyframeAnimations.degreeVec(187.69f, 103.57f, -170.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(182.37f, 98.83f, -158.38f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.458343f, KeyframeAnimations.degreeVec(194.87f, 98.83f, -158.38f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.083433f, KeyframeAnimations.degreeVec(179.82f, 25.06f, -182.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.343333f, KeyframeAnimations.degreeVec(163.27f, 10.3f, -162.36f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H1Jaw",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.208343f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.208343f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Biomass4",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.scaleVec(1.3f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.25f, KeyframeAnimations.scaleVec(1.3f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.75f, KeyframeAnimations.scaleVec(1.3f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.25f, KeyframeAnimations.scaleVec(1.3f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Biomass1",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2083435f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.208343f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Biomass2",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5416767f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.541677f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Biomass3",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT3Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-40.25f, 14.98f, 16.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9167665f, KeyframeAnimations.degreeVec(19.89f, 43.7f, 27.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.167667f, KeyframeAnimations.degreeVec(37.14f, 31.48f, 54.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H3Jaw",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(12.54f, -5.42f, 1.36f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5f, KeyframeAnimations.degreeVec(12.54f, -5.42f, 1.36f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT1Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(72.08f, -30.58f, -57.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(-88.05f, -24.68f, 105.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.958343f, KeyframeAnimations.degreeVec(-128.05f, -24.68f, 105.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MT2Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.2916765f, KeyframeAnimations.degreeVec(-33.61f, -17.72f, -24.61f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.916767f, KeyframeAnimations.degreeVec(57.38f, -24.09f, -20.37f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(52.93f, -15.48f, -7.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Tumor3",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1.3f, 1.3f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5f, KeyframeAnimations.scaleVec(1.3f, 1.3f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("H4Jaw",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(5f, 0f, -10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.8343335f, KeyframeAnimations.degreeVec(14.99f, -9.1f, -20.83f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Tumor1",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1.1f, 1.1f, 1.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4f, KeyframeAnimations.scaleVec(1.2f, 1.1f, 1.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.916767f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Tumor2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5f, KeyframeAnimations.degreeVec(13.68f, -8.3f, -7.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Tumor2",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1.2f, 1f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("Tendril4Seg3",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -50f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(27.5f, -50f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(-20.21f, -3.19f, 20.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.1676665f, KeyframeAnimations.degreeVec(59.79f, -3.19f, 20.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(18.34f, -2.89f, 96.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.375f, KeyframeAnimations.degreeVec(20.37f, 25.48f, 106.88f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.343333f, KeyframeAnimations.degreeVec(-15.52f, 6.27f, 112.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Tendril1Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(11.83f, -27.46f, 44.02f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.125f, KeyframeAnimations.degreeVec(80.54f, -0.37f, 39.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Tendril2Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.4583433f, KeyframeAnimations.degreeVec(0f, -57.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.375f, KeyframeAnimations.degreeVec(46.68f, -38.45f, -59.61f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7083435f, KeyframeAnimations.degreeVec(6.68f, -38.45f, -59.61f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.5416765f, KeyframeAnimations.degreeVec(6.37f, 1.28f, -30.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.degreeVec(-24.06f, -40.91f, -35.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.916767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Tendril3Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.375f, KeyframeAnimations.degreeVec(0f, -35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4583435f, KeyframeAnimations.degreeVec(60f, -35f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-11.69f, -64.44f, 51.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4583435f, KeyframeAnimations.degreeVec(-5.19f, -14.85f, 42.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(-14.17f, -6.86f, 87.47f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.708343f, KeyframeAnimations.degreeVec(-1.32f, 53.01f, 66.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.375f, KeyframeAnimations.degreeVec(1.35f, -6.9f, 49.84f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MG2Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.125f, KeyframeAnimations.degreeVec(22.5f, 0f, 40f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(9.01f, 20.7f, -25.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6766665f, KeyframeAnimations.degreeVec(110.61f, 11.16f, 65.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.834333f, KeyframeAnimations.degreeVec(69.63f, 49.35f, 18.97f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MG1Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-22.5f, 0f, 25f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.0416765f, KeyframeAnimations.degreeVec(24.19f, -21.68f, -13.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.625f, KeyframeAnimations.degreeVec(-10.99f, -63.79f, 54.58f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MG3Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.7916767f, KeyframeAnimations.degreeVec(0f, 0f, 80f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2083435f, KeyframeAnimations.degreeVec(0f, -22.5f, -17.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.375f, KeyframeAnimations.degreeVec(-93.34f, 54.96f, 29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.167667f, KeyframeAnimations.degreeVec(-56.27f, -7.52f, 53.92f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.25f, KeyframeAnimations.degreeVec(-55.61f, 2.33f, 39.43f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("MG4Seg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.0416767f, KeyframeAnimations.degreeVec(0f, 0f, -82.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.9167667f, KeyframeAnimations.degreeVec(0f, 0f, 20f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.6766665f, KeyframeAnimations.degreeVec(-20.47f, 43.85f, -98.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.9583435f, KeyframeAnimations.degreeVec(-15.75f, -3.27f, -69.99f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("HeadTumor2",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.scaleVec(1.4f, 1.3f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1.4f, 1.3f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.7083435f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.25f, KeyframeAnimations.scaleVec(1.4f, 1.3f, 1.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("HeadTumor1",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.5f, KeyframeAnimations.scaleVec(1.5f, 1.3f, 1.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(0.8f, 0.8f, 0.8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.5f, KeyframeAnimations.scaleVec(1.5f, 1.3f, 1.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H5Jaw",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7083433f, KeyframeAnimations.degreeVec(-5.04f, -7.47f, 0.66f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-0.04f, 12.53f, 0.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.4167665f, KeyframeAnimations.degreeVec(-0.04f, -9.97f, 0.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.041677f, KeyframeAnimations.degreeVec(-12.39f, 4.68f, -2.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.625f, KeyframeAnimations.degreeVec(-2.39f, 4.68f, -2.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.958343f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H5TorsoRight",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 32.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(4.625f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.375f, KeyframeAnimations.degreeVec(0f, 11.25f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(5.75f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H5TorsoLeft",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, -30f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5416767f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("H5Tumors",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083434f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(2.3433335f, KeyframeAnimations.scaleVec(1.1f, 1.1f, 1.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(3.7083435f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(4.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(5.291677f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
